### ISSUE TITLE
missing whole Custom Elements API

### ISSUE THREAD

**Issue by scalway** [scala-js/scala-js-dom#351] opened 2019-03-27 14:39 UTC
missing classes in 

org.scalajs.dom.raw:
- [ShadowRoot](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot) 
- [HTMLSlotElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement)
- [HTMLTemplateElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTemplateElement)

in Element:
```scala
/** Creates a shadow root for element and returns it. */
def attachShadow(init:js.Any):ShadowRoot
```
 
- [CustomElementRegistry](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry)

in Window:
```scala
def customElements:CustomElementRegistry
```

new interface that HTMLElement should extends 
```typescript
interface Slotable {
    readonly assignedSlot: HTMLSlotElement | null;
}
```

caniuse of  [ShadowDom](https://caniuse.com/#feat=shadowdomv1)

Should I send PR or we are not interested this API until it is covered by all browsers?

**Comment by sjrd** [comment] 2019-03-27 14:42
In general, we accept PRs for APIs that are specified in the DOM standard, unless there is some evidence that it *won't* be implemented in all browsers. If it's not *yet* implemented in all browsers, but it's standardized, that's fine.

**Comment by mseddon** [comment] 2019-03-31 22:05
That would usually live in the `org.scalajs.dom.experimental` sub package. The point being anything imported from `org.scalajs.dom` should always work across all supported browsers to minimise confusion.

**Comment by scalway** [comment] 2019-04-11 07:26
I leave it 4 now. Scalajs 0.6 does not compile ES2015 with Google Closure Compiler. It means we are not ready to write WebComponents using 0.6 tree yet. It could be useful for scalajs 1.0 (where fullOpt'll produce minified version) but not there yet. I have some code of it in my internal project but it needs to be polished a bit still. 

I'll continue my experiments with WebComponents when 1.0 version will be in RC state. Hopefully browser support'll increase up to then.

**Comment by mseddon** [comment] 2019-10-25 18:09
@sjrd I have been on a rather long hiatus from Scala so my information is embarrassingly out of date.

The issue with providing WebComponents 1.0 here is that it will require ES6 class syntax to even function (i.e. ECMAScript5 and below are a no-go). Does Scala.js produce ES6 or above out of the box now?

**Comment by sjrd** [comment] 2019-10-25 22:32
Scala.js 0.6.x had provided an option to emit ECMAScript 2015 (ES 6) for years:

    scalaJSLinkerConfig ~= { _.withESFeatures(_.withUseECMAScript2015(true)) }

Scala.js 1.0.0-M7 and above emit ECMAScript 2015 by default, and the same option with `false` can be used to force it to emit ES 5.1.

**Comment by armanbilge** [comment] 2021-08-11 02:44
@scalway at a quick glance it seems some of these APIs are more widely supported now, if you're still up for it we can consider a PR for the `experimental` package.

**Comment by armanbilge** [comment] 2021-08-11 03:30
Marking as duplicate of #191.

**Closed by armanbilge** 2021-08-11 03:30 UTC
Labels: duplicate, enhancement, help wanted
